### PR TITLE
Add a `TokioContext` executor.

### PR DESCRIPTION
**Pull request by obmarg**
Thanks for writing this library.  I'm writing [a library](https://github.com/obmarg/graphql-ws-client) that uses
async_executors to allow users to decide which runtime they want to use
with my library.  I developed it using async_std, and it works great.

But I'm having a bit of trouble with the tokio support - it's fairly
common for tokio applications to use `#[tokio::main]` on their main
function, which runs them inside a tokio executor.  But this means that
when you call `TokioTpBuilder::new().build()` you're creating another
executor in addition to the main one - and if you drop that inner
executor you'll get a panic:

> thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.',

So, this commit adds a `TokioContext` executor that'll just use the
existing tokio executor rather than creating a new one.

Apologies for probably not formatting some things correctly - I'm
usually a bit of a rustfmt obsessive.

### CODE REVIEW

**Comment by najamelan** [comment]
Hi, thanks for the contribution.

I'm fine accommodating this use case, but I think we should create a `TokioTp` or `TokioCt` depending on what kind of executor it is. I'm afraid this would require tokio to expand their API as to allow something like `Runtime::current() -> Option<Runtime>` and for `Runtime` to be inspectable, that is have methods like `is_current()` and `is_multi()`. Btw if the `tokio::runtime::Builder` were inspectable like this, our API would be much smoother and not require builder types, as we could just take the `tokio::runtime::Builder` in our constructor rather than having our own builder types. And we could provide `TokioTp::from_current()` and `TokioCt::from_current()`.

Would you like to check with the tokio project if they would be open to such extensions on the API? 

The alternative is of course for application developers not to use the attributes and Deliberately create their runtimes. I feel it are two somewhat different coding styles, as in one you say "I want to always be able to call `tokio::spawn` anywhere", and in the other you say: "I know exactly what and where my executor is and if anything needs it, it's passed round as a parameter."

As for the formatting, like [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md) says, don't worry about it.

**Comment by obmarg** [comment]
> I'm fine accommodating this use case, but I think we should create a TokioTp or TokioCt depending on what kind of executor it is

Maybe I'm misunderstanding, but wouldn't this be quite tricky to encode in the type system?  Can't _usually_ return a different type based on a boolean.  Unless you're just suggesting doing some validation.

> The alternative is of course for application developers not to use the attributes and Deliberately create their runtimes. I feel it are two somewhat different coding styles, as in one you say "I want to always be able to call tokio::spawn anywhere", and in the other you say: "I know exactly what and where my executor is and if anything needs it, it's passed round as a parameter."

Yeah, for sure.  Although tokio does fairly heavily push you towards using `tokio::main` (their `Runtime` docs specifically say
`most users will use the #[tokio::main] annotation on their entry point instead`).  I've also yet to see a tokio based library that doesn't expect to be run inside a tokio context (although I've not looked too far tbf).

I'm not the biggest fan of this aspect of tokio (I would probably rather the approach you suggest, or the one async_std takes) but it does seem to be their preferred approach.

**Comment by najamelan** [comment]
> Maybe I'm misunderstanding, but wouldn't this be quite tricky to encode in the type system? Can't _usually_ return a different type based on a boolean. Unless you're just suggesting doing some validation.

If we have `TokioTp::current()` and `TokioCt::current()`, each function will return a different type. People should know what kind of executor they are running. However, I do think the tokio attribute macro changes that depending on which features are enabled, so it could mean this changes under peoples nose when some of their dependencies enable features. At least by requiring them to be conscious about it they will notice that and can think about whether it's a good thing.

That being said, you can perfectly return multiple types by using an enum.

> I'm not the biggest fan of this aspect of tokio (I would probably rather the approach you suggest, or the one async_std takes) but it does seem to be their preferred approach.

What are you referring to? Last time I checked,  the async_std executor is always global, and it is always a threadpool, with no configuration possible.

**Comment by obmarg** [comment]
> If we have `TokioTp::current()` and `TokioCt::current()`, each function will return a different type. 
>

So are you proposing that we:

1. Add these `Runtime::is_current` & `Runtime::is_multi` functions to tokio
2. Create `TokioTP::current` & `TokioCt::current` functions that take the current runtime, and do something like `assert!(current_runtime.is_current())` to make sure they're called in the right context?

> People should know what kind of executor they are running. However, I do think the tokio attribute macro changes that depending on which features are enabled, so it could mean this changes under peoples nose when some of their dependencies enable features. At least by requiring them to be conscious about it they will notice that and can think about whether it's a good thing.

If I remember correctly `tokio::main` always uses the multi threaded runtime by default, and forces you to specify the single threaded runtime if you use it without the `rt-multi-thread` feature enabled.  

That said, I'm not sure if it's always obvious to users which style of runtime they're using.  [`async_compat`](https://docs.rs/async-compat/0.2.1/async_compat/) specifically puts things on a single threaded runtime even if there's already an existing multi-threaded runtime elsewhere in the app.  Which has certainly resulted in some confusion in services I work on.

> What are you referring to? Last time I checked, the async_std executor was always global, and it was always a threadpool, with no configuration possible. Maybe I missed some more recent changes to async_std.

No, I think you're correct - I just like that the `async_std` executor is global without config options rather than thread local and requiring explicit setup.   Just my personal preference though, and not that important for this issue here.

**Comment by najamelan** [comment]
> * Add these `Runtime::is_current` & `Runtime::is_multi` functions to tokio
> 
> * Create `TokioTP::current` & `TokioCt::current` functions that take the current runtime, and do something like `assert!(current_runtime.is_current())` to make sure they're called in the right context?

 `Runtime::current() -> Option<Runtime>` and for Runtime to be inspectable, that is have methods like `is_current()` and `is_multi()`.

And we could provide `TokioTp::from_current()` and `TokioCt::from_current()`. -> These would return an option or a result. No panicking needed.

> If I remember correctly `tokio::main` always uses the multi threaded runtime by default

Not [by default](https://github.com/tokio-rs/tokio/blob/8f6d8b25bf27adec804326d306fc2e217816408a/tokio/Cargo.toml#L27).

**Comment by qiujiangkun** [comment]
You can refer to https://github.com/najamelan/async_executors/issues/8, where I suggest adding a ZST to represent the context executor. https://github.com/qiujiangkun/async_executors/blob/e8008287197d257360fe3ec4e45f88dbf0c909e1/src/runtime/tokio_static.rs

**Comment by akiradeveloper** [comment]
Hello, I am new to this library. I am trying to make my [library](https://github.com/akiradeveloper/norpc) runtime agnostic.

I am also wondering how to use the current tokio runtime. What is the best solution as of v0.6.0?

**Comment by najamelan** [comment]
hi @akiradeveloper. If I understand right, you would like to use a global executor. This library is all about being able to specify your requirements by trait bounds, APIs like:

```rust
fn some_fun( exec: impl Spawn )
```
Any implementation of a global spawn function is out of scope for this library. If you wanted to create it, you sure could use this lib to provide the executors, but putting the executor in a global var/thread local is up to you.

If that is not what you are after, please look at the examples directory in the repository as well as doc.rs API docs.

**Comment by akiradeveloper** [comment]
@najamelan I see. Thank you!

**Comment by teohhanhui** [comment]
Hmm... There's https://docs.rs/tokio/latest/tokio/runtime/struct.Handle.html#method.runtime_flavor

I wonder if that'd help...

**Comment by najamelan** [comment]
Actually I'm working quite long hours. It might have to wait until the weekend.

**Comment by Sytten** [comment]
Can we revisit this?

**Comment by najamelan** [comment]
Yes, sorry for the delays. Will try to implement this this weekend.

**Comment by najamelan** [comment]
Ok, I think I have a design that works:

- will allow creation of the tokio executors from either `Runtime` or `Handle`. 
- will use the `runtime_flavor` to make sure you cannot create the wrong one.
- will add a convenience method `from_current` that will use `Handle::try_current` to try and get the current tokio runtime.
- you won't be able to call the shutdown functions if we were created from a handle, but will add an error type so you get clear feedback on why the call fails
- will remove the builder helpers because we don't need them anymore. 
- you will have to make sure the `Runtime`/current tokio runtime have the correct features set like timers and io as it wont be able to add those after the runtimes are created. I will add a `Default` impl for basic usage that will respect the features selected on `async_executors` like the builders used to and for convenience/brevity of creating a basic runtime.

Does that sound good?

**Comment by najamelan** [comment]
This is a commit with the code. I need to update the tests/docs, then should be good to go:
https://github.com/najamelan/async_executors/commit/5b8e7197a41d72c4d84a6717d092f106dca8e6e2

**Comment by Sytten** [comment]
Yup sounds exactly like what I would expect!

**Comment by najamelan** [comment]
I will make sure to properly document the `TryFrom`. I'll make it return a `WrongFlavour` error variant. The reason is to have the flavour expressed in the type. If you need to spawn a future that isn't `Send`, you can take `impl LocalSpawnHandle`. A multithreaded runtime cant implement this.

**Comment by najamelan** [comment]
Actually it's a hassle. As I want to give the caller back their runtime, it would need to be in the error type. This makes the error type not `Clone` as `Runtime` isn't, and then we'd need a second variant on the error type for the other `TryFrom` from `Handle`. User's will have to read the docs if they want to understand why it fails.

**Comment by teohhanhui** [comment]
> This makes the error type not `Clone`

Hardly unusual, I think.

https://doc.rust-lang.org/stable/std/io/struct.Error.html#trait-implementations

**Comment by najamelan** [comment]
Ok, latest commit on dev is feature complete. Docs and tests still need some work, so I will try to finalize that over the next few days and publish a new version. Feel free to test with a patch to the git version.

Note that creating the executor from an already entered runtime is discouraged and has footguns. It means that `block_on` now panics as you are already in an async context. Specifically for the `current thread` version that can be confusing. The behavior of the type now depends on how it was created, which is meh. I personally wouldn't use it. I don't see the win going from:

```rust
fn main()
{
   let exec = TokioTp::new().expect( "setup executor" );
}
```
to:

```rust
#[tokio::main]
async fn main() {
   let exec = TokioTp::try_current().expect( "setup executor" );
}
```
The latter is an antipattern with footguns and no upsides really. But on popular demand it will be supported.

**Comment by teohhanhui** [comment]
> The latter is an antipattern with footguns and no upsides really.

As I've explained before, there are use cases where you can't prevent other code from using the tokio runtime directly. So this is the only way it's going to work.

**Comment by Sytten** [comment]
@najamelan What I have seen in the past is that some sync library crates using async dependencies will decide for you the runtime executor and this often causes problems if you are calling this sync lib from an async environment. Rust is a mess on that point for sure.

**Comment by najamelan** [comment]
version 0.7 has been released now allowing you to create the tokio executors from an entered Runtime. I have yet to add an `enter` method to the types which might be useful as well, but for now you can always create/enter your runtime first, then create the async_executor type.

**Pull request closed without merging**
