### PR TITLE
blocking join handle

### PR DESCRIPTION
**Pull request by qiujiangkun**
This implements BlockingJoinHandle for future use(SpawnBlocking)

### CODE REVIEW

**Comment by qiujiangkun** [comment]
Current blocking handle lacks `std::thread::JoinHandle`. Would you like to add it?

**Comment by najamelan** [comment]
I don't want to manually handle thread pools in async_executors. I will add spawn_blocking support to the other executors by the `blocking` crate. I will close this PR as blocking handle is now implemented.

**Comment by qiujiangkun** [comment]
Now the `#[must_use]` of the `BlockingHandle` is misleading. Please fix it.

**Comment by najamelan** [comment]
> Now the `#[must_use]` of the `BlockingHandle` is misleading. Please fix it.

Well spotted. I removed it, since the only consequence is that you cannot get the output if you don't keep the handle, but I consider the user will know when they want the output...

**Pull request closed without merging**
